version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: phptframework-web
    ports:
      - "80:80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: phptframework-db
    environment:
      MYSQL_DATABASE: phptframework
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - phptframework_mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped

volumes:
  phptframework_mysql_data:
